# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuessingGame-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GuessingGame-desktop

end

target 'GuessingGame-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GuessingGame-mobile

end
